fix:게시글 URL categoryName으로 통일
KEEPER31337/Homepage-Front pull request #275
Opened 2022-11-17 01:40 UTC by jasper200207

- 게시판에서 param으로 categoryId를 사용하는 반면, 유저프로필에서는 param으로 categoryName을 사용하여 카테고리가 정확하게 안떴다.
- 게시판에서도 categoryName을 param으로 사용하도록 변경
- categoryName은 categoryId와 달리 중복되는 경우가 있는 듯하다.

#264

2022-11-17 07:40 UTC, llddang commented
수고하셨습니다!

2022-11-17 07:42 UTC, llddang approved these changes

2022-11-17 07:42 UTC, llddang commented on src/page/Board/Components/Info.jsx
> +  useEffect(() => {}, [categoryName]);
`useEffect(() => {}, [categoryName]);`은 따로 하는 일 없는 것 같은데 빼도 좋을 것 같습니다!

2022-11-18 12:53 UTC, jasper200207 commented on src/page/Board/Components/Info.jsx
> +  useEffect(() => {}, [categoryName]);
반영해서 푸시했습니다!

2022-11-18 13:36 UTC, publdaze commented on src/page/Board/BoardUtil.jsx
> +        categoryMapper[key].name == name && categoryMapper[key].parent != 0
동등 연산자(`==`)를 사용할 경우 형변환이 일어나 어떠한 오류를 불러 일으킬 지 모르니 위험하다고 합니다! 엄격한 동등 연산자(`===`)를 추천 드립니다! ([참고](https://velog.io/@jangws/4.-eqeq-%EC%A4%84%EC%9D%B4%EA%B8%B0))

2022-11-18 13:36 UTC, publdaze commented on src/page/Board/Components/Boards.jsx
> +  const currentCategoryId = findCategoryByCategoryName(categoryName).id;
`findCategoryByCategoryName` 라는 함수명이 카테고리 이름으로 카테고리를 찾는 함수라는 게 바로 와닿아서 좋은 것 같아요! 👍 그리고 이렇게 카테고리를 찾는 로직을 함수로 따로 빼주니 가독성도 더 좋네요! 굿굿!

2022-11-18 13:36 UTC, publdaze commented on src/page/Board/Components/categoryMapper.js
>    },
`categoryMapper`에서 id를 `key`값으로 가지고 있는데 `id`라는 속성이 내부에 또 있는 게 의미 중복이라고 생각됩니다.
위에서 카테고리 이름으로 카테고리를 찾은 후 id 값을 얻기 위해 `id` 속성을 추가 하신 것 같은데 이것 외에 `id`값이 `key`에 있는데 `id`를 따로 넣은 특별한 이유가 있나요??

카테고리 이름이 필요한 경우는 `useParams`로 다 얻는 것 같은데 객체 속성으로 `name`을 얻는 경우가 필요하지 않으면 `key`값으로 `name`을 넣고 `name` 속성을 `key`로 두는 건 어떤가요?
ex)
```js
'게시판': {
  id: 2,
  parent: 0,
}
```
이렇게 하면 `findCategoryByCategoryName`으로 카테고리를 구한 후 id를 얻었던 것을 `categoryMapper[categoryName]?.id`로 바로 구할 수 있을 것 같습니다!

2022-11-18 13:38 UTC, publdaze commented on src/page/Board/Components/categoryMapper.js
>    },
아 `categoryName`이 중복되는 경우가 있나요? 확인해보고 오겠습니다!

2022-11-18 13:42 UTC, publdaze commented on src/page/Board/Components/categoryMapper.js
>    },
> categoryName은 categoryId와 달리 중복되는 경우가 있는 듯하다.

혹시 이거 어떤 경우가 있을까요?

2022-11-18 13:44 UTC, jasper200207 commented on src/page/Board/Components/categoryMapper.js
>    },
정보가 정보카테고리안에 정보 게시판이 있어서 중복됩니다

2022-11-18 14:10 UTC, publdaze commented on src/page/Board/Components/categoryMapper.js
>    },
흐음 그렇네요.. 카테고리 이름을 바꾸는 게 좋으려나... 다른 분들은 의견 어떤지 궁금합니다!

2022-11-18 15:24 UTC, jasper200207 commented on src/page/Board/BoardUtil.jsx
> +        categoryMapper[key].name == name && categoryMapper[key].parent != 0
새로운 정보 감사합니다! 반영해서 푸시했습니다!

2022-11-19 06:41 UTC, publdaze requested changes

2022-11-19 06:41 UTC, publdaze commented on src/page/Board/BoardUtil.jsx
> +        categoryMapper[key].name === name && categoryMapper[key].parent != 0
`!=`도 `!==`로 변경하면 좋을 것 같습니다!

+) 커밋은 변경한 내용에 대한 내용으로 적어주면 좋을 것 같습니다!
이 경우를 예를 들면
`refactor : 형변환으로 인한 오류 방지로 엄격한 동등 연산자 적용`
으로 하면 좋을 것 같습니다! 같은 pr이라도 세부적인 내용은 다르니까 커밋 메시지가 조금 더 구체화되면 좋을 것 같네요!

+) 해당 커밋 자체는 버그를 수정한 게 아닌 기능 상에는 변동이 없는 코드에 관련한 부분이니까 `refactor` 타입으로 해줘야 할 것 같습니다.

+) 커밋에 타입과 내용 사이 `:` 앞 뒤로 띄어쓰기 부탁드립니다!

2022-11-19 13:40 UTC, llddang commented on src/page/Board/Components/categoryMapper.js
>    },
카테고리 이름을 한 번 총정리하는 것이 좋다고 생각합니다!

2022-11-19 14:48 UTC, jasper200207 commented on src/page/Board/Components/categoryMapper.js
>    },
아니면 카테고리에만 사용하는 이름과 게시판에 사용하는 이름을 구분하는 것도 좋을거 같습니다

2022-11-19 14:52 UTC, jasper200207 commented on src/page/Board/BoardUtil.jsx
> +        categoryMapper[key].name === name && categoryMapper[key].parent != 0
반영했습니다!

2022-11-20 15:08 UTC, jasper200207 commented
카테고리정리 포함해서 푸시했습니다

2022-11-21 06:00 UTC, publdaze approved these changes

2022-11-21 06:04 UTC, merged