Feature/프로필 글자반응형 #265
KEEPER31337/Homepage-Front pull request #280
Opened 2022-11-19 07:07 UTC by mia2583

반응형 페이지의 크기에 따라 글자가 나눠지는 문제를 해결했습니다.
tailwind 코드로 수정하고 싶었는데, 한글을 띄어쓰기로 분리해주는 word-break:keep-all의 경우는 없어서 style로 적용했습니다.

그리고 비밀번호 수정 기능에서 비밀번호 입력 칸 크기도 수정했습니다.

#265

2022-11-19 08:16 UTC, publdaze requested changes
프리티어 적용이 안되는 것 같은데 문제가 뭔지 제가 확인해보겠습니다!

2022-11-19 08:16 UTC, publdaze commented on src/page/Profile/EditProfile.jsx
> +                          style={{wordBreak:"keep-all"}}
tailwind css에 `wordBreak:"keep-all"`를 나타내는 `break-keep`이 존재합니다! style로 따로 분리 하지 말고 className에 `break-keep` 추가해주면 좋을 것 같습니다! ([참고](https://tailwindcss.com/docs/word-break))

2022-11-20 15:13 UTC, mia2583 commented on src/page/Profile/EditProfile.jsx
> +                          style={{wordBreak:"keep-all"}}
className="p-2 w-5/12 text-gray-500 break-keep" 처럼 className에 break-keep 넣어서 수정해봤는데...적용이 안되네요. 
이것도 다른 word-break 종류처럼 영어에만 가능하고 한글에는 적용이 안되는 거 같습니다.

2022-11-23 02:13 UTC, publdaze commented on src/page/Profile/EditProfile.jsx
> +                          style={{wordBreak:"keep-all"}}
!! 나중에 한 번 확인해보겠습니다!

2022-11-27 11:58 UTC, publdaze commented on src/page/Profile/EditProfile.jsx
> +                          style={{wordBreak:"keep-all"}}
확인 완! 그냥 style로 가져갑시다!

2022-11-27 11:59 UTC, publdaze approved these changes

2022-11-27 12:03 UTC, llddang approved these changes

2022-11-27 13:48 UTC, mia2583 commented on src/page/Profile/EditProfile.jsx
> +                          style={{wordBreak:"keep-all"}}
> 혹시 `style={{wordBreak:"keep-all"}}`로 설정하면 한글에도 적용이 되는 걸까요?

@llddang 
네 keep-all로 하면 한글에도 적용됩니다!

2022-11-27 13:53 UTC, merged