Feature/랭킹 직책 띄우기 #267
KEEPER31337/Homepage-Front pull request #281
Opened 2022-11-19 09:28 UTC by mia2583

제가 수정 중에 pull을 받아서 제 변경 사항이 아닌 다른 사람의 변경 사항이 함께 반영되어 있어요. 
리뷰 시 참고하세요!

랭킹 페이지에서 회원마다 직책 정보 띄우도록 수정했습니다.

2022-11-19 09:32 UTC, amaran-th approved these changes

2022-11-19 09:36 UTC, publdaze requested changes

2022-11-19 09:36 UTC, publdaze commented on src/page/Ranking/Component/RankingTable.jsx
> +    //console.log('result', result);
이부분 지워줘도 될 것 같습니다!

2022-11-19 09:36 UTC, publdaze commented on src/page/Ranking/Component/RankingTable.jsx
> +                          //{console.log(member)}
필요없는 주석은 지워주세요!

2022-11-20 11:01 UTC, publdaze requested changes

2022-11-20 11:01 UTC, publdaze commented on src/page/Ranking/Component/RankingTable.jsx
> +                          //{console.log(member)}
<img width="894" alt="image" src="https://user-images.githubusercontent.com/78250089/202898496-550604b9-10e5-4845-b44d-90bc76ddbdcd.png">

이부분 주석이 중괄호 내부가 아닌 앞에 넣어서 텍스트로 인식합니다! 그로인해서 랭킹에 `//`이라는 텍스트가 들어가고 한칸씩 밀리게 되네요!! 주석 지우면 정상적으로 돌아갈 것 같습니다!

2022-11-20 11:07 UTC, publdaze commented on src/page/Ranking/Component/RankingTable.jsx
> +                          //{console.log(member)}
<img width="894" alt="image" src="https://user-images.githubusercontent.com/78250089/202898644-6d2583a9-64ce-40f2-bf06-6984fbd33311.png">

주석 처리를 중괄호 밖으로 하여서 주석이 아닌 텍스트로 들어갔네요!
그래서 랭킹에 `//`이라는 텍스트가 들어가면서 테이블이 한 칸씩 밀린 것 같습니다! 주석 부분 제거하면 정상적으로 동작할 것 같아요!

+) 태그 사이에 script 주석 넣으려면 `{ /*console.log(member)*/ }` 이런 식으로 해주면 됩니다!

2022-11-20 15:20 UTC, mia2583 commented on src/page/Ranking/Component/RankingTable.jsx
> +    //console.log('result', result);
넵 수정했습니다!

2022-11-20 15:20 UTC, mia2583 commented on src/page/Ranking/Component/RankingTable.jsx
> +                          //{console.log(member)}
앗...제가 제대로 확인을 안했네요...
수정했습니다!!

2022-11-22 15:29 UTC, llddang approved these changes
수고하셨습니다!

2022-11-23 04:02 UTC, merged

2022-11-23 14:29 UTC, publdaze reviewed
pr 재오픈 하겠습니다!