fix : 헤더에 키퍼로고 & 프로필부분 반응형 처리
KEEPER31337/Homepage-Front pull request #297
Opened 2022-11-26 06:38 UTC by jasper200207

- 기존에 화면넓이가 줄었을 때 이미지와 버튼의 넓이도 줄어드는 부분 수정
- 로고 이미지크기 xl부터 크기 줄어들도록 변경
- 로고 이미지와 카테고리 사이의 여백 lg이하부터 축속
- 카테고리의 텍스트크기 lg 이하부터 축소
- 카테고리와 프로필버튼 사이의 마진 제거

#286

2022-11-27 05:17 UTC, publdaze requested changes
<img width="866" alt="image" src="https://user-images.githubusercontent.com/78250089/204120004-89eb24af-f374-4e71-b4fc-3de102a20462.png">

가로 넓이 `864px` 정도에 카테고리들이 전체적으로 좌측에 치우쳐져 있는데 중앙 정렬 되게하면 좋을 것 같습니다!

2022-11-30 07:56 UTC, jasper200207 commented
> <img alt="image" width="866" src="https://user-images.githubusercontent.com/78250089/204120004-89eb24af-f374-4e71-b4fc-3de102a20462.png">
> 
> 가로 넓이 `864px` 정도에 카테고리들이 전체적으로 좌측에 치우쳐져 있는데 space-between 속성처럼 좌우 균등하게 퍼지는? 형태로 되게하면 좋을 것 같습니다!

반영하여 다시 푸시했습니다.

2022-12-02 00:01 UTC, publdaze reviewed
<img width="544" alt="image" src="https://user-images.githubusercontent.com/78250089/205180892-8303b34e-7167-4aec-b599-7c7d63998999.png">
카테고리 hover했을 때 뜨는 아래 방향 꺽쇠(?)가 왼쪽의 카테고리에 해당하는 요소인데 오른쪽 카테고리와 너무 가까운 것 같습니다! 사이 간격을 더 띄우는 건 어떨까요?

2022-12-02 01:36 UTC, jasper200207 commented on src/shared/Component/UserBox.jsx
> +              {member.memberInfo.nickName == 'test02' && '00'}
앗 테스트코드 지우는거 까먹었습니다....

2022-12-05 06:59 UTC, jasper200207 commented
> <img alt="image" width="544" src="https://user-images.githubusercontent.com/78250089/205180892-8303b34e-7167-4aec-b599-7c7d63998999.png">
> 
> 카테고리 hover했을 때 뜨는 아래 방향 꺽쇠(?)가 왼쪽의 카테고리에 해당하는 요소인데 오른쪽 카테고리와 너무 가까운 것 같습니다! 사이 간격을 더 띄우는 건 어떨까요?

간격 추가했습니다!

2022-12-05 23:47 UTC, publdaze commented
커밋이 `fix 카테고리 반응형 처리`으로 올라왔는데
커밋 타입과 제목 사이에 ` : ` 넣는 거 깜박하신 것 같아요!

그리고 `fix` 타입의 경우 저희 [리뉴얼1 노션](https://enormous-button-c5d.notion.site/Github-18f082ce71e541008a5bb70495b48005)에도 적혀 있지만

![image](https://user-images.githubusercontent.com/78250089/205768803-57abb59d-1893-4b9e-9119-0198f4e7e99d.png)

버그 수정할 때 사용 하는 타입입니다!

`숨어있던 테스트 코드 제거` 같은 경우는 저희가 의도하지 않은 결과가 나오므로 `fix` 타입을 사용할 수 있지만 단순히 css를 수정한 경우에는 저희가 자체적으로 정했던 타입중 `design` 타입을 사용하면 더 좋을 것 같습니다!

2022-12-05 23:53 UTC, publdaze approved these changes

2022-12-24 02:12 UTC, lcqff approved these changes

2022-12-24 03:02 UTC, closed without merging

2022-12-24 03:08 UTC, publdaze commented
깃헙에서 오류 발생한 것 같습니다 정상적으로 머지 되지 않아 다시 pr 날리고 머지해두겠습니다!