feat : CTF 새탭으로 페이지 링크 열리도록
KEEPER31337/Homepage-Front pull request #307
Opened 2022-11-29 14:07 UTC by pipisebastian

- CTF + 키퍼위키도 새탭으로 열리게
- 기존 키퍼위키처럼 카테고리 속성에 external: true를 둠.
-  external: true를 갖는것들을 새탭으로 열리게 처리

#283

2022-11-30 00:47 UTC, llddang commented
수고하셨습니다!
근데 제가 듣기론 CTF 창이 새탭으로 뜨는 것이 아닌 CTF들의 문제들이 새탭으로 뜨게 만드는 것으로 알고 있습니다
@publdaze 맞는지 확인 부탁드립니다!
그리고 저번 회의에 pr제목을 featur명과 동일하게 작성하기로 했습니다!
또 pr 내용안에 issue 링크 남기기로 정했습니다!
참고바랍니당!

2022-11-30 01:12 UTC, publdaze commented
> 수고하셨습니다! 근데 제가 듣기론 CTF 창이 새탭으로 뜨는 것이 아닌 CTF들의 문제들이 새탭으로 뜨게 만드는 것으로 알고 있습니다 @publdaze 맞는지 확인 부탁드립니다! 그리고 저번 회의에 pr제목을 featur명과 동일하게 작성하기로 했습니다! 또 pr 내용안에 issue 링크 남기기로 정했습니다! 참고바랍니당!

맞습니다! CTF페이지 말고 CTF 문제 안의 링크를 새탭으로 띄우려는 의도였습니다!

2022-11-30 04:58 UTC, pipisebastian commented on src/shared/Component/HeaderPopDown.jsx
> +                          target="_blank"
페이지를 새창 또는 새탭으로 열기 위해서는
target 속성을 추가하고, 그 값을 '_blank'로 지정해야합니다!

2022-11-30 05:02 UTC, pipisebastian commented
> 

넹...

2022-11-30 05:22 UTC, publdaze commented on src/shared/Component/HeaderPopDown.jsx
> +                          target="_blank"
오홍! 그러면 `external: false` 되어 있을 때는 `_blank` 지정해도 새탭으로 안 열리나요?

2022-12-02 18:15 UTC, llddang commented
수고하셨습니다!!

2022-12-02 18:17 UTC, llddang approved these changes

2022-12-03 17:52 UTC, publdaze requested changes

2022-12-03 17:52 UTC, publdaze commented on src/shared/Component/HeaderPopDown.jsx
> +                          target="_blank"
이 부분은 헤더에서 바로 새탭 띄우려고 했을 때 작성했던 코드 같은데 문제의 링크를 새탭으로 띄우는 데도 필요한가요?~? 필요 없다면 지워주면 좋을 것 같습니다!

2022-12-03 17:52 UTC, publdaze commented on src/page/CTF/Components/ChallengeModal.jsx
> +                          linkAttributes={{
ToastUIEditor Viewer API 옵션에 `linkAttributes`라는 속성도 있었군요! 제공되는 API를 잘 활용하셨네요! 👍👍

2022-12-06 00:16 UTC, publdaze commented on src/shared/Component/HeaderPopDown.jsx
> +                          target="_blank"
아 pr 설명에

> external: true를 갖는것들을 새탭으로 열리게 처리

이부분을 보고 a태그에 `external` 이라는 attributes가 따로 있는 줄 알았는데 `external`이 그냥 저희가 정의하여 쓰는 것이었네요! 착각했습니다! 감사합니다~!

2022-12-06 00:22 UTC, publdaze commented on src/shared/Component/HeaderPopDown.jsx
> +                          target="_blank"
`external`으로 지정한 카테고리에 대해서 해당 부분이 렌더링 되는 것 이제 이해했습니다. 위키의 경우 그대로 새탭으로 띄워지게 해도 괜찮을 것 같습니다!

2022-12-06 00:24 UTC, publdaze approved these changes

2022-12-11 04:54 UTC, merged