ctf 글자 overflow 처리 #285
KEEPER31337/Homepage-Front pull request #308
Opened 2022-11-30 04:56 UTC by pipisebastian

- ctf메인 페이지 - 대회 이름, 설명 overflow처리
- ctf 챌린지 페이지 - 카드(문제 이름) oveflow처리
- ctf 챌린지 페이지 - 모달창 문제이름 글자 흐르도록 처리
- 스코어보드 페이지 - 테이블 overflow처리
- ctf 팀 페이지 -  solves 테이블 overflow처리
- 문제관리 페이지 - 테이블 overflow처리
- 제출로그 페이지 - 테이블 overflow처리
- 대회운영 페이지 - 백엔드상에서 글자제한을 이미 막아놓음
- 네비게이션 팀이름 overflow처리
- #285

2022-11-30 05:23 UTC, llddang approved these changes
하나하나 바꾸시느라 수고하셨습니다!!

2022-11-30 05:23 UTC, llddang approved these changes

2022-12-01 18:07 UTC, amaran-th approved these changes
수고하셨습니다~~

2022-12-02 00:08 UTC, publdaze requested changes
<img width="806" alt="image" src="https://user-images.githubusercontent.com/78250089/205184980-e568b012-2ab9-4e8e-b3ab-fa9085edd62b.png">
많은 경우 다 처리해주시느라 수고 많으셨습니다!
추가적으로 글자가 시작하는 부분이 너무 딱 붙는 것 같던데 padding을 넣어주거나 해서 살짝 간격을 띄워주는 건 어떨까요?

2022-12-02 00:13 UTC, publdaze requested changes
<img width="1728" alt="image" src="https://user-images.githubusercontent.com/78250089/205185360-34d43f09-1138-47af-a377-a5f4f86eeef1.png"> 
<img width="1728" alt="image" src="https://user-images.githubusercontent.com/78250089/205185681-9e856766-27fc-4dac-b357-48bc8072480b.png">

추가적으로 팀페이지에도 안쪽 빨간 라인 안에 위치하도록 하면 좋을 것 같습니다!

2022-12-02 18:33 UTC, llddang approved these changes

2022-12-03 18:32 UTC, publdaze approved these changes
- https://github.com/KEEPER31337/Homepage-Front/issues/285
이슈 설명에 추가적으로 수정해야 하는 부분 적어두었습니다.
수정할 사항이 꽤 있는 관계로 해당 pr은 머지하고 다른 pr로 추가 수정 사항 날리는 걸로 합니다!

2022-12-04 03:35 UTC, merged