Feature/세미나 출석 관련 알람 띄우기 #259
KEEPER31337/Homepage-Front pull request #310
Opened 2022-12-02 09:21 UTC by lcqff

2022-12-02 10:05 UTC, publdaze requested changes
main으로 머지되도록 돼있습니다! develop으로 수정 부탁드려요!

2022-12-02 13:56 UTC, publdaze commented
prettier가 적용되면서 코드 변경 사항이 너무 많아 어느 부분 작업하셨는 지 파악이 어려워서 그런데 코드 상에서 어느 부분인 지 집어줄 수 있을까요?

2022-12-02 14:06 UTC, publdaze commented
세미나 출석 관련 알람 띄우는 건 버그 수정 보다는 기능 추가인 것 같습니다! 이 경우는 커밋 타입에 `fix`보단 `feat`을 써주면 좋을 것 같네요!
그리고 커밋이 두 가지가 올라 왔는데 커밋 제목이 같습니다. 커밋 본문을 보면 다른 걸 알 수 있지만 커밋 제목에서도 각각 커밋의 작업 내용을 한 눈에 파악할 수 있도록 작성하면 좋을 것 같아요! 🙂

2022-12-02 14:10 UTC, llddang commented
> prettier가 적용되면서 코드 변경 사항이 너무 많아 어느 부분 작업하셨는 지 파악이 어려워서 그런데 코드 상에서 어느 부분인 지 집어줄 수 있을까요?

인정합니다ㅠㅠ 진심으로

2022-12-03 19:10 UTC, publdaze requested changes

2022-12-03 19:10 UTC, publdaze commented on src/page/Clerk/AutoAttend.jsx
> +                    {' '}
텍스트에 공백 들어간 상태로 prettier가 적용되면서 이 부분이 추가된 것 같습니다. 공백 넣은 게 의도한 게 아니라면 제거해주면 좋을 것 같습니다!

2022-12-04 00:49 UTC, lcqff commented
> > prettier가 적용되면서 코드 변경 사항이 너무 많아 어느 부분 작업하셨는 지 파악이 어려워서 그런데 코드 상에서 어느 부분인 지 집어줄 수 있을까요?
> 
> 인정합니다ㅠㅠ 진심으로

크아아악 이제보니 개난리네요 남겼습니다!!!

2022-12-04 00:49 UTC, lcqff commented
> 세미나 출석 관련 알람 띄우는 건 버그 수정 보다는 기능 추가인 것 같습니다! 이 경우는 커밋 타입에 `fix`보단 `feat`을 써주면 좋을 것 같네요! 그리고 커밋이 두 가지가 올라 왔는데 커밋 제목이 같습니다. 커밋 본문을 보면 다른 걸 알 수 있지만 커밋 제목에서도 각각 커밋의 작업 내용을 한 눈에 파악할 수 있도록 작성하면 좋을 것 같아요! 🙂

네!!!

2022-12-04 13:46 UTC, llddang requested changes

2022-12-04 13:46 UTC, llddang commented on src/page/Clerk/Components/AutoAttend/DoAttend.jsx
> +  };
css 스타일로 하신 이유가 있을까요?
tailwind도 변수로 만들어서 사용가능합니다!

2022-12-04 13:46 UTC, llddang commented on src/page/Clerk/AutoAttend.jsx
> +          if (res.data.isExist) setSeminarExist(true);
if(res.success)로 한번 확인하고 가는 것이 좋을것 같습니다. 만약 성공하지 않는다면 data가 undefined로, isExist 를 확인하는 과정에서 에러가 날 것 같습니다
아니면 간단하게 ?로 처리해줘도 될 것 같습니다!

2022-12-10 12:34 UTC, publdaze commented on src/page/Clerk/AutoAttend.jsx
> +      .substring(0, 10);
이부분은 저희가 사용하고 있는 라이브러리중 `dayjs`라이브러리를 사용하여
`dayjs(startDate).format('YYYY-MM-DD')` 이렇게 간단하게 얻을 수 있을 것 같습니다!

2022-12-12 06:05 UTC, llddang commented on src/page/Clerk/AutoAttend.jsx
> +          if (res.data.isExist) setSeminarExist(true);
헐룽.. 뭐지? 잘 못 봤나봅니다!

2022-12-12 06:06 UTC, llddang approved these changes

2023-01-07 05:51 UTC, publdaze approved these changes

2023-01-07 07:37 UTC, merged