Feature/페이지 블럭 타이틀 수정 기능 #288
KEEPER31337/Homepage-Front pull request #314
Opened 2022-12-04 03:12 UTC by mia2583

페이지 블럭 타이틀 수정 버튼을 만들고 input을 통해 수정할 수 있습니다.
기존의 타이틀 값을 받아와서 input에 디폴트로 띄우고 ,
수정 완료 후에도 새로 저장한 타이틀 값이 페이지에  출력 되도록 했습니다.
- #288

2022-12-04 10:33 UTC, amaran-th approved these changes

2022-12-04 15:15 UTC, publdaze commented on src/page/About/Component/Activity.jsx
> +              ref={titleInput}
여기서 ref는 왜 달아준 건가요?

2022-12-04 15:15 UTC, publdaze commented on src/page/About/Component/Activity.jsx
> +            </>
`button`이라는 하나의 DOM element만 존재하는데 상위에 fragment(`<></>`)로 감쌀 필요는 없어보입니다. 혹시 따로 감싸주신 이유가 있을까요?

2022-12-04 23:36 UTC, mia2583 commented on src/page/About/Component/Activity.jsx
> +  const sectionTitle = activityInfo[0].title;
네 삭제했습니다!!

2022-12-04 23:39 UTC, mia2583 commented on src/page/About/Component/Activity.jsx
> +              ref={titleInput}
원래는 수정 버튼을 누르면 입력창이 focus 되도록 코드를 작성했습니다. 그런데 { editTitleMode && (...) } 에 대해 적용하니까 동작이 제대로 안되어서 해당 코드를 삭제 했습니다. 
삭제하는 도중에 제가 누락한 거 같아요. 다음엔 제대로 확인하겠습니다~!!

2022-12-04 23:40 UTC, mia2583 commented on src/page/About/Component/Activity.jsx
> +            </>
어어..딱히 없어요...;;저때...무슨 생각이었을까요....
삭제 했습니다!

2022-12-05 00:09 UTC, publdaze commented on src/page/About/Component/Excellence.jsx
> +  const [editTitleMode, setEditTitleMode] = useState(false);
boolean 변수 네이밍 할 때 어떻게 하면 좋을 지 고민되는 경우 제가 자주 보는 [블로그 글](https://soojin.ro/blog/naming-boolean-variables) 공유드립니다!
`editTitleMode`의 경우는 수정 가능 상태인지 아닌지를 나타내는 변수이므로
- `isTitleEditMode`
- `canTitleEdit` (-> can은 잘 써본 적이 없어서 마음에 안 들긴 하네요!)

이런 느낌으로 지을 수 있을 것 같습니다!

2022-12-05 02:09 UTC, publdaze commented on src/page/About/Component/Activity.jsx
> +            </>
ㅋㅋㅋㅋㅋㅋ 굿굿!

2022-12-05 03:46 UTC, mia2583 commented on src/page/About/Component/Activity.jsx
> +          )}
오옹 여기에도 삼항 연산자를 적용할 수 있네요! 전혀 생각도 못했습니다....!
이 부분도 수정했습니닷~!

2022-12-05 05:18 UTC, publdaze requested changes

2022-12-05 05:18 UTC, publdaze commented on src/page/About/Component/Activity.jsx
> +  }, [activityInfo]);
이부분 `useEffect` 내부 코드를 보면 `setActivityInfo(data.list);`가 포함되어 있습니다. `activityInfo`가 변할 때 마다 실행이 되는데 내부에서 activityInfo를 변경하니 API 무한 반복 호출하게 됩니다. 이부분 우선적으로 수정 부탁드립니다!

2022-12-05 08:02 UTC, mia2583 commented on src/page/About/Component/Activity.jsx
> +  }, [activityInfo]);
일단 수정했습니다. 한번 확인해주세요!

2022-12-06 13:37 UTC, publdaze requested changes

2022-12-06 13:37 UTC, publdaze commented on src/page/About/Component/Activity.jsx
> +          });
`changeTitle` 함수로 api 호출 시 response 값으로 수정된 결과 값을 반영합니다.

API 문서에 보면 response로 어떤 값을 주고 있는 지 확인할 수 있습니다!
<img width="400" alt="image" src="https://user-images.githubusercontent.com/78250089/205925451-1f608fbd-28d7-47ba-a80b-d3d44f2d9f3e.png">

새로 수정된 결과 값을 얻기 위해 get API를 호출할 필요없이 응답으로 받은 값 (여기서는 `res.data`로 얻을 수 있겠네요!)
을 사용하여 `activityInfo`를 업데이트 해주면 될 것 같습니다

2022-12-06 23:26 UTC, mia2583 commented on src/page/About/Component/Activity.jsx
> +          });
허억...그렇네요, 앞서 호출한 changeTitle의 결과를 이용할 수 있군요!👍👍👍
바로 리팩토링 했습니닷.

2022-12-07 14:22 UTC, publdaze commented on src/page/About/Component/Activity.jsx
> +    setIsTitleEditMode(!isTitleEditMode);
이전 state를 바탕으로 새로운 state를 얻고  싶다면 callback function을 인자로 넣어주면 좋을 것 같습니다!

`setIsTitleEditMode((prevTitleEditMode) => !prevTitleEditMode);`

이렇게 하면 `prevTitleEditMode`가 확실히 이전값이라는 걸 보장할 수 있습니다!

2022-12-07 14:28 UTC, publdaze commented on src/page/About/Component/Activity.jsx
> +    setIsTitleEditMode(!isTitleEditMode);
`useState` 관련해서 찾아보다가 [이러한 글](https://www.philly.im/blog/things-to-know-about-use-state#%EB%B3%B4%EB%84%88%EC%8A%A4-2-usereducer%EB%A1%9C-state-%ED%86%A0%EA%B8%80-%ED%95%98%EA%B8%B0)을 발견했습니다!

`useReducer`라는 훅도 있네요!! 단순 토글의 역할인 경우 `useReducer`를 사용하면 더 깔끔해질 것 같습니다!

링크된 글 useReducer 부분 말고도 전체적으로 유익한 것 같습니다! 시간되면 전체적으로 한 번 읽어보면 좋을 것 같아요😁

2022-12-12 06:03 UTC, llddang approved these changes

2023-01-07 12:18 UTC, closed without merging